// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "show-relate-tags": boolean;
      "current-collection": boolean;
      "selected-collection": boolean;
      "children-collection": boolean;
      "count-down-close": number;
      "count-down-close-dec": number;
      "optional-color": string;
      "max-show": number;
      "tags-exclude": string;
      "sort": string;
      "combine-nested-tags": boolean;
      "split-nested-tags-keep-first": boolean;
      "split-nested-tags-keep-second": boolean;
      "show-query-href": boolean;
      "google-scholar-mirroring": string;
      "isCtrlAdd": boolean;
      "windowType": string;
      "blockHUToggle": boolean;
      "show-selected-popup-match-tag": boolean;
      "fixed-tags-colors": string;
    };
  }
}
